name: Test React App and Push Docker Registry

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]

    steps:
      - name: Checkuot repo
        uses: actions/checkout@v3

      - name: Testing with Node ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: Build and test react app
        run: |
          cd codebase/rdicidr-0.1.0
          npm install
          npm run lint
          npm install prettier
          npm run prettier
          CI=true npm run test
          npm run build

  build_push_docker:
    needs: build_test
    runs-on: ubuntu-latest

    steps:
      - name: Checkuot repo
        uses: actions/checkout@v3

      - name: Login on docker hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Setup docker builder
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Get repo name
        id: repo_name
        shell: bash
        run: echo "##[set-output name=repo;]$(echo ${GITHUB_REPOSITORY#*/})"

      - name: Build and push image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./codebase/rdicidr-0.1.0
          file: ./codebase/rdicidr-0.1.0/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/${{steps.repo_name.outputs.repo}}:latest
